-- Transaktion 2 fur Dirty Read, die mit Read
--DEFAUL AVEM COMMITED READ si pt a avea aceasta anomalie trebuie sa punem pe UNCOMMITED READ
--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

BEGIN TRANSACTION T2
SELECT * FROM Modele
WHERE Nach_Name = 'Hadid'
COMMIT TRANSACTION T2
